# Generated by Django 6.0.3 on 2026-04-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('day', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=100)),
                ('priority', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolists.todolist')),
            ],
        ),
        migrations.AddIndex(
            model_name='todolist',
            index=models.Index(fields=['user', 'created_at'], name='index_on_created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together={('title', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('priority', 'todo_list')},
        ),
    ]
